/// <reference path="../../src/assets/assets.d.ts" />
import cloudSo from './icons/cloud-so.png';
import cloudSunSo from './icons/cloud-sun-so.png';
import cloudySo from './icons/cloudy-so.png';
import configSo from './icons/config-so.png';
import folderCo from './icons/folder-co.png';
import folderSo from './icons/folder-so.png';
import folderTr from './icons/folder-tr.png';
import gearCo from './icons/gear-co.png';
import gearTr from './icons/gear-tr.png';
import previewSo from './icons/preview-so.png';
import trashSo from './icons/trash-so.png';
import trashTr from './icons/trash-tr.png';
import cloudSun from './icons/weather/cloud-sun.png';
import tile000 from './icons/weather/tile000.png';
import tile001 from './icons/weather/tile001.png';
import tile002 from './icons/weather/tile002.png';
import tile003 from './icons/weather/tile003.png';
import tile004 from './icons/weather/tile004.png';
import tile005 from './icons/weather/tile005.png';
import tile006 from './icons/weather/tile006.png';
import tile008 from './icons/weather/tile008.png';
import tile009 from './icons/weather/tile009.png';
import tile010 from './icons/weather/tile010.png';
import tile011 from './icons/weather/tile011.png';
import tile012 from './icons/weather/tile012.png';
import tile013 from './icons/weather/tile013.png';
import tile014 from './icons/weather/tile014.png';
import tile016 from './icons/weather/tile016.png';
import tile017 from './icons/weather/tile017.png';
import tile018 from './icons/weather/tile018.png';
import tile019 from './icons/weather/tile019.png';
import tile020 from './icons/weather/tile020.png';
import tile021 from './icons/weather/tile021.png';
import tile022 from './icons/weather/tile022.png';
declare type Png = {
    cloudSo: typeof cloudSo;
    cloudSunSo: typeof cloudSunSo;
    cloudySo: typeof cloudySo;
    configSo: typeof configSo;
    folderCo: typeof folderCo;
    folderSo: typeof folderSo;
    folderTr: typeof folderTr;
    gearCo: typeof gearCo;
    gearTr: typeof gearTr;
    previewSo: typeof previewSo;
    trashSo: typeof trashSo;
    trashTr: typeof trashTr;
    cloudSun: typeof cloudSun;
    tile000: typeof tile000;
    tile001: typeof tile001;
    tile002: typeof tile002;
    tile003: typeof tile003;
    tile004: typeof tile004;
    tile005: typeof tile005;
    tile006: typeof tile006;
    tile008: typeof tile008;
    tile009: typeof tile009;
    tile010: typeof tile010;
    tile011: typeof tile011;
    tile012: typeof tile012;
    tile013: typeof tile013;
    tile014: typeof tile014;
    tile016: typeof tile016;
    tile017: typeof tile017;
    tile018: typeof tile018;
    tile019: typeof tile019;
    tile020: typeof tile020;
    tile021: typeof tile021;
    tile022: typeof tile022;
};
export type { Png };
